apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: crossplane-example-db
  namespace: platform
spec:
  providerConfigRef:
    name: platform
  forProvider: 
    connectionLimit: -1
  writeConnectionSecretToRef:
    namespace: platform
    name: example-secret
  providerConfigRef:
    name: default
