apiVersion: database.crossplane.io/v1alpha1
kind: PostgresDatabase
metadata:
  name: example-db
spec:
  forProvider:
    name: example-provider
    kind: PostgresInstance
    connectionDetails:
      secret:
        name: example-secret
        key: connection-string
  name: example-db