apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: crossplane-example-db
  namespace: platform
spec:
  providerConfigRef:
    name: platform
  forProvider:
    name: postgres-db
    kind: PostgresInstance
  name: crossplane-example-db
