apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: crossplane-example-db
  namespace: platform
spec:
  providerConfigRef:
    name: platform
  forProvider: 
    createMode: Default
    administratorLogin: postgres
    resourceGroupNameSelector:
      matchControllerRef: true
    minimalTlsVersion: TLS1_2
    sslEnforcement: Disabled
  writeConnectionSecretToRef:
    namespace: platform
    name: example-secret
  providerConfigRef:
    name: default
