apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: example-db
  namespace: platform
spec:
  forProvider:
    name: example-provider
    kind: PostgresInstance
    connectionDetails:
      secret:
        name: example-secret
        key: connection-string
  name: example-db