apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: crossplane-system
type: Opaque
stringData:
  username: postgres
  password: postgres
  endpoint: postgres-service
  port: "5432"
